apiVersion: v2
name: cronjobs
version: 2.0.1
description: Kubernetes Cron Jobs
type: application
dependencies:
  - name: common
    repository: "file://../common"
    version: ^2.0.0
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/cronjobs
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
