{{- $allJobs := default dict .Values.jobs -}}
{{- range $key, $value := $allJobs -}}
{{- $localSecrets := ($value.env | default dict).vaultSecret | default dict -}}
{{- if $localSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $key }}-vault
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: vault
  vaultRole: {{ $.Release.Namespace }}
  kvVersion: 2
  data:
    {{- range $key, $value := $localSecrets }}
    - name: {{ $key }}
      key: {{ if $value.fullPath -}}
        {{- $value.fullPath -}}
        {{- else -}}
        secret-{{ $.Values.global.org }}/data/
        {{- $.Values.global.environmentType -}}
        /k8s/{{ $.Release.Namespace}}/{{ $value.path }}
      {{- end }}
      property: {{ default $key $value.secret }}
    {{- end -}}
{{- end -}}
{{- end -}}
