{{ if .Values.env.vaultSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" . }}-vault
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.global.org -}}-{{- $.Values.global.project -}}-{{- $.Values.global.environment }}
    kind: SecretStore
  refreshInterval: "3m"
  target:
    name: {{ include "k8s-common.names.fullname" . }}-vault
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
  {{- $allVaultSecrets := default (dict) .Values.env.vaultSecret -}}
  {{- range $key, $value := $allVaultSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ if $value.fullPath -}}
          {{- $value.fullPath -}}
        {{- else -}}
          kv/data/
          {{- $.Values.global.org -}}/
          {{- $.Values.global.project -}}/
          {{- $.Values.global.environment -}}/
          {{- $value.path }}
        {{- end }}
        property: {{ default $key $value.secret }}
  {{ end -}}
{{ end -}}

{{- range .Values.sidecarContainers }}
{{- $values := dict "Values" (merge . (dict "global" $.Values.global)) "Release" $.Release "Template" $.Template -}}
{{ if and (hasKey $values.Values "env") (hasKey $values.Values.env "vaultSecret") }}
{{ $name := default $.Release.Name $.Values.global.serviceName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" $values }}-vault
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.global.org -}}-{{- $.Values.global.project -}}-{{- $.Values.global.environment }}
    kind: SecretStore
  refreshInterval: "3m"
  target:
    name: {{ include "k8s-common.names.fullname" $values }}-vault
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
  {{- $allVaultSecrets := default (dict) $values.Values.env.vaultSecret -}}
  {{- range $key, $value := $allVaultSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ if $value.fullPath -}}
          {{- $value.fullPath -}}
          {{- else -}}
          kv/data/
          {{- $.Values.global.org -}}/
          {{- $.Values.global.project -}}/
          {{- $.Values.global.environment -}}/
          {{- $value.path }}
        {{- end }}
        property: {{ default $key $value.secret }}
  {{ end -}}
{{ end -}}
{{ end -}}

{{- range .Values.initContainers }}
{{- $values := dict "Values" (merge . (dict "global" $.Values.global)) "Release" $.Release "Chart" $.Chart "Template" $.Template -}}
{{ if and (hasKey $values.Values "env") (hasKey $values.Values.env "vaultSecret") }}
{{ $name := default $.Release.Name $.Values.global.serviceName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" $values }}-vault
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.global.org -}}-{{- $.Values.global.project -}}-{{- $.Values.global.environment }}
    kind: SecretStore
  refreshInterval: "3m"
  target:
    name: {{ include "k8s-common.names.fullname" $values }}-vault
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
  {{- $allVaultSecrets := default (dict) $values.Values.env.vaultSecret -}}
  {{- range $key, $value := $allVaultSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ if $value.fullPath -}}
          {{- $value.fullPath -}}
          {{- else -}}
          kv/data/
          {{- $.Values.global.org -}}/
          {{- $.Values.global.project -}}/
          {{- $.Values.global.environment -}}/
          {{- $value.path }}
        {{- end }}
        property: {{ default $key $value.secret }}
  {{ end -}}
{{ end -}}
{{ end -}}

{{- if .Values.vaultVolumesSupport -}}
{{- $allVolumes := default (dict) .Values.volumes -}}
{{- range $key, $value := $allVolumes }}
{{- if $value.vaultPath -}}
{{- $vaultPath := $value.vaultPath }}
{{- $items := default (list) $value.items }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" $ }}-vault-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.global.org -}}-{{- $.Values.global.project -}}-{{- $.Values.global.environment }}
    kind: SecretStore
  refreshInterval: "3m"
  target:
    name: {{ include "k8s-common.names.fullname" $ }}-vault-{{ $key }}
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
  {{- range $items }}
    - secretKey: {{ . }}
      remoteRef:
        key: kv/data/
          {{- $.Values.global.org -}}/
          {{- $.Values.global.project -}}/
          {{- $.Values.global.environment -}}/
          {{- $vaultPath }}
        property: {{ . }}
    {{ end -}}
  {{ end -}}
  {{ end -}}
{{- end -}}
