{{- if and .Values.ingress.enabled .Values.service.enabled ( eq .Values.service.type "ClusterIP") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
  annotations:
  {{- include "k8s-common.ingress.annotations" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
      {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $ ) | nindent 4 }}
    {{- end }}

spec:
  rules:
    - host: {{ include "k8s-common.ingress.host" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" "ssl-redirect" "servicePort" "use-annotation" "context" $)  | nindent 14 }}
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            {{- if and (eq .Values.rollouts.strategy "canary") .Values.rollouts.enabled }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (include "k8s-common.ingress.serviceName" .) "servicePort" "use-annotation" "context" $)  | nindent 14 }}
            {{- else }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (include "k8s-common.ingress.serviceName" .) "servicePort" "http" "context" $)  | nindent 14 }}
            {{- end }}

    {{- if and (eq .Values.rollouts.strategy "blueGreen") .Values.rollouts.enabled }}
    - host: preview-{{ include "k8s-common.ingress.host" . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (include "k8s-common.ingress.previewServiceName" .) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{ range .Values.ingress.extraHosts -}}
    {{- $portName := default "http" .port -}}
    - host: {{ required "A valid ingress.extraHosts.host entry required!" .host | quote }}
      http:
        paths:
          {{ if .paths -}}
          {{ range .paths -}}
          - path: {{ . }}
            pathType: {{ $.Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (include "k8s-common.ingress.serviceName" $) "servicePort" $portName "context" $)  | nindent 14 }}
          {{ end -}}
          {{ else -}}
          - path: "/"
            pathType: Prefix
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" "ssl-redirect" "servicePort" "use-annotation" "context" $)  | nindent 14 }}
          {{ end -}}
    {{ end -}}
{{- end }}
