{{- $globalSecrets := default dict $.Values.env.vaultSecret -}}
{{- if $globalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-vault
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  refreshInterval: "3m"
  target:
    name: {{ $.Release.Name }}-{{ $.Chart.Name }}-vault
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
    {{- range $key, $value := $globalSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ if $value.fullPath -}}
          {{- $value.fullPath -}}
        {{- else -}}
          secret-{{ $.Values.global.product }}/data/
          {{- $.Values.global.environment -}}
          /k8s/{{ $value.path }}
        {{- end }}
        property: {{ default $key $value.secret }}
    {{- end -}}
{{- end -}}

{{- $allCronJobs := default dict .Values.cronjobs -}}
{{- range $key, $value := $allCronJobs -}}
{{- $localSecrets := ($value.env | default dict).vaultSecret | default dict -}}
{{- if $localSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $key }}-vault
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  refreshInterval: "3m"
  target:
    name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $key }}-vault
    template:
      metadata:
        annotations:
          external-secret: "true"
  data:
    {{- range $key, $value := $localSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ if $value.fullPath -}}
          {{- $value.fullPath -}}
        {{- else -}}
          secret-{{ $.Values.global.product }}/data/
          {{- $.Values.global.environment -}}
          /k8s/{{ $value.path }}
        {{- end }}
        property: {{ default $key $value.secret }}
    {{- end -}}
{{- end -}}
{{- end -}}
