{{- $globalSecrets := default dict $.Values.env.vaultSecret -}}
{{- if $globalSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-vault
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: vault
  vaultRole: {{ $.Release.Namespace }}
  kvVersion: 2
  data:
    {{- range $key, $value := $globalSecrets }}
    - name: {{ $key }}
      key: {{ if $value.fullPath -}}
        {{- $value.fullPath -}}
        {{- else -}}
        secret-{{ $.Values.global.product }}/data/
        {{- $.Values.global.environment -}}
        /k8s/{{ $value.path }}
      {{- end }}
      property: {{ default $key $value.secret }}
    {{- end -}}
{{- end -}}


{{- $allCronJobs := default dict .Values.cronjobs -}}
{{- range $key, $value := $allCronJobs -}}
{{- $localSecrets := ($value.env | default dict).vaultSecret | default dict -}}
{{- if $localSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $key }}-vault
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: vault
  vaultRole: {{ $.Release.Namespace }}
  kvVersion: 2
  data:
    {{- range $key, $value := $localSecrets }}
    - name: {{ $key }}
      key: {{ if $value.fullPath -}}
        {{- $value.fullPath -}}
        {{- else -}}
        secret-{{ $.Values.global.product }}/data/
        {{- $.Values.global.environment -}}
        /k8s/{{ $value.path }}
      {{- end }}
      property: {{ default $key $value.secret }}
    {{- end -}}
{{- end -}}
{{- end -}}
