{{- $allKubeSecrets := default (dict) .Values.kubeSecrets -}}
{{- $namespace := .Release.Namespace }}
{{- range $key, $value := $allKubeSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}-vault
  namespace: {{ $namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: {{ $key }}-vault
  data:
  {{- $allVaultSecrets := default (dict) $value -}}
  {{- range $vaultValue := $allVaultSecrets }}
  - secretKey: {{ $vaultValue.name }}
    remoteRef:
      key: secret-{{ $.Values.global.product }}/data/
      {{- $.Values.global.environment -}}
      /k8s/{{ $vaultValue.path }}
      property: {{ default $vaultValue.name $vaultValue.secret }}
  {{ end -}}
{{ end -}}
