{{- $allKubeSecrets := default (dict) .Values.kubeSecrets -}}
{{- $namespace := .Release.Namespace }}
{{- range $key, $value := $allKubeSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}-vault
  namespace: {{ $namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $.Values.global.org -}}-{{- $.Values.global.project -}}-{{- $.Values.global.environment }}
    kind: ClusterSecretStore
  target:
    name: {{ $key }}-vault
  data:
  {{- $allVaultSecrets := default (dict) $value -}}
  {{- range $vaultValue := $allVaultSecrets }}
  - secretKey: {{ $vaultValue.name }}
    remoteRef:
      key: kv/data/
        {{- $.Values.global.org -}}/
        {{- $.Values.global.project -}}/
        {{- $.Values.global.environment -}}/
        {{ $vaultValue.path }}
      property: {{ default $vaultValue.name $vaultValue.secret }}
  {{ end -}}
{{ end -}}
