---
# Default values for sso-roles chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Global parameters
## Global Docker image parameters
global:
  ## @param global.project The product of the service
  ##
  product: ""
  ## @param global.serviceName Name of the service. Affects public DNS.
  ## E.g. cherry-admin, tpt-service-api
  ##
  serviceName: "example"
  ## @param global.environment Type of the environment, one of "dev", "stage", "prod".
  ##
  environment: "dev"
  ## @param global.domain Company Root-level domain, expects
  ## [<global.project>.<global.environment>].<global.domain> Route53 HZ.
  ##
  domain: ""
## @section Common parameters
## @param nameOverride By default, name uses '{{ .Chart.Name }}'.
## This overrides that and uses the given string instead.
##
nameOverride: ""
## @param fullnameOverride By default, fullname uses '{{ .Release.Name }}-{{ .Chart.Name }}'.
## This overrides that and uses the given string instead.
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param githubActionsIntegration Allow github runners to create resources in namespace
## E.g.
## githubActionsIntegration: true
githubActionsIntegration: false
